/* global window */
'use strict';

window.JOBS = [
  {
    id: 1,
    title: "SDE Intern",
    company: "Amazon",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Data Structures", "Algorithms", "Problem Solving"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹30k–₹40k/month",
    applyUrl: "https://amazon.jobs/en/teams/internships",
    description: "Amazon is looking for SDE Interns to join our Customer Experience team in Hyderabad. You will work alongside senior engineers to design, build, and ship features used by millions of customers globally. You will participate in code reviews, write production-grade code, and contribute to sprint planning. Interns are treated as full team members with ownership over real deliverables. Strong problem-solving skills and a solid foundation in data structures and algorithms are required."
  },
  {
    id: 2,
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Communication", "Aptitude"],
    source: "Naukri",
    postedDaysAgo: 0,
    salaryRange: "3.5–4 LPA",
    applyUrl: "https://www.tcs.com/careers/india/freshers",
    description: "TCS is hiring Graduate Engineer Trainees across all engineering disciplines for its Bengaluru delivery centre. Selected candidates will undergo a comprehensive 3-month training programme covering programming, databases, and business communication. Upon successful completion, trainees are placed on live client projects across domains including BFSI, retail, and healthcare. This role offers structured career progression within TCS's global delivery model."
  },
  {
    id: 3,
    title: "Junior Backend Developer",
    company: "Razorpay",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Node.js", "PostgreSQL", "REST APIs", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–16 LPA",
    applyUrl: "https://razorpay.com/jobs/backend-developer",
    description: "Razorpay's payments infrastructure team is hiring a Junior Backend Developer to work on core payment processing systems handling billions of rupees daily. You will be building and maintaining high-availability microservices, writing robust API integrations, and participating in on-call rotations. The role demands a strong understanding of distributed systems, relational databases, and caching strategies. Experience with payment gateways is a bonus but not required."
  },
  {
    id: 4,
    title: "Frontend Intern",
    company: "Swiggy",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹25k–₹35k/month",
    applyUrl: "https://careers.swiggy.com/frontend-intern",
    description: "Swiggy is looking for a Frontend Intern to work with our consumer app team in Bengaluru. You will help build and optimise UI components used by millions of diners placing orders every day. The internship involves hands-on React development, working closely with senior engineers and designers to ship features across web and mobile web. Curiosity, attention to detail, and a genuine interest in user experience are valued highly."
  },
  {
    id: 5,
    title: "QA Intern",
    company: "Capgemini",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Test Cases", "Selenium basics", "JIRA"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹20k/month",
    applyUrl: "https://www.capgemini.com/careers/qa-intern",
    description: "Capgemini India is hiring QA Interns for its Quality Engineering practice in Mumbai. Interns will be responsible for writing and executing manual test cases, documenting defects in JIRA, and supporting senior QA engineers. You will gain exposure to enterprise software testing methodologies and best practices across web and API layers. This is a 6-month internship with a possibility of a full-time offer based on performance."
  },
  {
    id: 6,
    title: "Data Analyst Intern",
    company: "Flipkart",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel", "Data Visualisation"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹30k–₹45k/month",
    applyUrl: "https://careers.flipkart.com/data-analyst-intern",
    description: "Flipkart's Analytics & Insights team is seeking a Data Analyst Intern to support business decisions across its e-commerce marketplace. You will write SQL queries, build dashboards, and assist in analysing seller, customer, and logistics data. The role offers exposure to large-scale datasets and Flipkart's proprietary data infrastructure. Strong quantitative thinking and proficiency in Python's data libraries are essential."
  },
  {
    id: 7,
    title: "Java Developer (0–1 yr)",
    company: "Infosys",
    location: "Pune",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "Hibernate", "MySQL"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "4–6 LPA",
    applyUrl: "https://www.infosys.com/careers/apply/java-developer",
    description: "Infosys BPM is hiring Java Developers with 0–1 year of experience for its BFSI delivery team in Pune. You will be joining an agile delivery squad working on modernisation of legacy banking applications using Spring Boot. Responsibilities include coding, unit testing, and debugging features as per technical specifications. Freshers who completed relevant Java certifications or personal projects are strongly encouraged to apply."
  },
  {
    id: 8,
    title: "Python Developer (Fresher)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "REST APIs", "PostgreSQL"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "4–7 LPA",
    applyUrl: "https://zoho.com/careers/python-developer",
    description: "Zoho Corporation is hiring Python Developers for its cloud-platform team based in Chennai. You will be building internal tooling and customer-facing SaaS modules using Django and PostgreSQL. Zoho's strong engineering culture values ownership, simplicity, and curiosity over credentials. Freshers with strong project portfolios or open-source contributions are welcomed. The role comes with a competitive compensation package and full health benefits."
  },
  {
    id: 9,
    title: "React Developer (1–3 yrs)",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "GraphQL", "Figma"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "8–14 LPA",
    applyUrl: "https://freshworks.com/company/careers/react-developer",
    description: "Freshworks is hiring a React Developer to join its CX platform team in Chennai. You will own the development of customer-facing dashboard modules used by over 50,000 growing businesses worldwide. The role requires strong TypeScript skills, familiarity with design systems, and the ability to translate Figma designs to pixel-perfect, accessible React components. You will collaborate with product managers and backend engineers in a fast-paced agile environment."
  },
  {
    id: 10,
    title: "Graduate Engineer Trainee",
    company: "Wipro",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["C++", "Java", "Communication", "Problem Solving"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "3.5–4.5 LPA",
    applyUrl: "https://careers.wipro.com/freshers",
    description: "Wipro is recruiting Graduate Engineer Trainees for its ELITE National Talent Hunt program across engineering disciplines. Successful candidates join an intensive foundation training programme at Wipro's learning campus before being deployed to client projects. The programme is designed to build full-stack engineering capabilities within six months. Stipend and benefits are provided during the training period, with confirmation into a full role upon successful assessment."
  },
  {
    id: 11,
    title: "Junior DevOps Engineer",
    company: "PhonePe",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD", "Bash"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://phonepe.com/en-in/careers/devops-engineer",
    description: "PhonePe's Platform Engineering team is hiring a Junior DevOps Engineer to support its high-scale financial infrastructure running over 5 billion transactions annually. You will manage CI/CD pipelines, container orchestration on Kubernetes, and AWS infrastructure-as-code. The role demands reliability engineering mindset with an eye for automation opportunities. Strong scripting skills and experience with observability tooling such as Grafana or Datadog are preferred."
  },
  {
    id: 12,
    title: "Data Analyst Intern",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Tableau", "Business Analysis"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "₹20k–₹30k/month",
    applyUrl: "https://paytm.com/about-us/careers/data-analyst-intern",
    description: "Paytm's Growth Analytics team is looking for a Data Analyst Intern to support merchant and consumer acquisition campaigns. You will build automated reporting pipelines, create Tableau dashboards, and assist in A/B test analysis. The role sits at the intersection of business strategy and data engineering, giving you broad exposure to fintech analytics. Prior experience with large datasets or academic research projects is a plus."
  },
  {
    id: 13,
    title: "Frontend Intern",
    company: "CRED",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS", "UI/UX awareness"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹35k–₹50k/month",
    applyUrl: "https://careers.cred.club/frontend-intern",
    description: "CRED is hiring a Frontend Intern for its consumer app web team. You will work on high-impact product surfaces used by India's creditworthy population of 10 million+ members. CRED places an extremely high bar on design quality and UI craftsmanship — you must care about pixel accuracy, accessibility, and performance. This internship is a proving ground for exceptional engineers who pay attention to the smallest of details."
  },
  {
    id: 14,
    title: "SDE Intern",
    company: "Juspay",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Haskell", "Functional Programming", "Linux", "Problem Solving"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹40k–₹60k/month",
    applyUrl: "https://juspay.in/careers/sde-intern",
    description: "Juspay, India's leading payments orchestration platform, is hiring SDE Interns with a passion for functional programming. You will contribute to the core payment routing and checkout platform built in Haskell, processing millions of transactions. Juspay runs an unconventional engineering culture that rewards deep thinking over volume of output. Prior experience with functional languages (Haskell, Erlang, or Elm) is preferred but not mandatory for exceptional candidates."
  },
  {
    id: 15,
    title: "Junior Backend Developer",
    company: "Meesho",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "FastAPI", "MongoDB", "Kafka"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "9–14 LPA",
    applyUrl: "https://meesho.io/careers/backend-developer",
    description: "Meesho's Seller Platform team is looking for a Junior Backend Developer to build scalable services for its network of 15 million+ resellers. You will own backend features end-to-end, from design to deployment, working in a microservices and event-driven architecture powered by Kafka. The team values autonomy, speed, and a product-first mindset. Candidates with experience in social commerce or marketplace platforms are particularly welcome."
  },
  {
    id: 16,
    title: "QA Analyst (0–1 yr)",
    company: "Accenture",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Selenium", "JUnit", "API Testing", "Agile"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "4.5–6.5 LPA",
    applyUrl: "https://accenture.com/in-en/careers/qa-analyst",
    description: "Accenture's Quality Engineering practice is scaling its test automation capabilities and is hiring QA Analysts with up to one year of experience. You will be responsible for creating and maintaining Selenium test scripts, performing API testing using Postman, and documenting defects in an agile scrum environment. Training on Accenture's proprietary testing framework will be provided. The role is client-facing with opportunity for international travel."
  },
  {
    id: 17,
    title: "React Developer (1–3 yrs)",
    company: "BrowserStack",
    location: "Mumbai",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "JavaScript", "Testing", "WebSockets"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "12–18 LPA",
    applyUrl: "https://browserstack.com/careers/react-developer",
    description: "BrowserStack is hiring a React Developer to work on the Live and Automate product lines used by over 50,000 engineering teams globally. You will be building interactive browser testing UIs, real-time WebSocket-based session views, and developer-facing dashboards. BrowserStack operates with a fully distributed engineering culture, giving you complete flexibility and trust to deliver. Prior experience with developer tooling or testing infrastructure is highly desirable."
  },
  {
    id: 18,
    title: "Python Developer (Fresher)",
    company: "Freshworks",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Flask", "REST APIs", "SQL"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "5–8 LPA",
    applyUrl: "https://freshworks.com/company/careers/python-developer-fresher",
    description: "Freshworks is hiring graduate Python Developers for its platform engineering team in Chennai. You will join a team responsible for building the internal API gateway and developer platform that powers Freshworks' suite of SaaS products. The role involves Python API development, SQL schema design, and integration with third-party services. Freshworks runs a structured onboarding programme designed specifically for fresh graduates with strong fundamentals."
  },
  {
    id: 19,
    title: "Graduate Engineer Trainee",
    company: "Cognizant",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "HTML", "Communication"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "4–5 LPA",
    applyUrl: "https://careers.cognizant.com/freshers",
    description: "Cognizant Technology Solutions is hiring Graduate Engineer Trainees through its GenC (Generation Cognizant) programme for its Pune delivery centre. You will undergo six weeks of technical and behavioural training before being allocated to a project stream. Cognizant works with Fortune 500 clients across banking, insurance, retail, and manufacturing. The programme has a clear progression path to Mid-Level Associate within 18–24 months."
  },
  {
    id: 20,
    title: "SDE Intern",
    company: "Zepto",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Golang", "Microservices", "System Design basics", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹40k–₹60k/month",
    applyUrl: "https://www.zeptonow.com/careers/sde-intern",
    description: "Zepto, India's 10-minute grocery delivery startup, is hiring SDE Interns to work on its core supply-chain and delivery orchestration systems. You will build backend services in Golang, working on real-time inventory management at massive scale. The engineering environment is fast, high-stakes, and deeply technical — if you want to learn more in 6 months than in 2 years elsewhere, this is the role. Prior Golang experience is a plus but not mandatory."
  },
  {
    id: 21,
    title: "Junior Backend Developer",
    company: "Groww",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "Kafka", "microservices"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–16 LPA",
    applyUrl: "https://groww.in/p/careers/backend-developer",
    description: "Groww is hiring a Junior Backend Developer for its Wealth platform engineering team. You will build reliable, low-latency APIs that power mutual fund and stock transactions for over 10 million investors. The systems you build must meet exchange-grade reliability and compliance requirements, which means a strong culture of testing, observability, and incident response. Spring Boot, Kafka, and AWS experience are preferred. You will grow fast here."
  },
  {
    id: 22,
    title: "Data Analyst Intern",
    company: "Nykaa",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Looker", "E-commerce analytics"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "₹20k–₹28k/month",
    applyUrl: "https://nykaa.com/careers/data-analyst-intern",
    description: "Nykaa's Marketing Analytics team is looking for a Data Analyst Intern to support campaign measurement and customer cohort analysis. You will work with large-scale e-commerce event data, write SQL queries, and build reports in Looker. Understanding of marketing funnels and e-commerce KPIs such as ROAS, LTV, and NPS is a plus. The internship runs for 3 months with a potential PPO for high performers."
  },
  {
    id: 23,
    title: "QA Intern",
    company: "Whatfix",
    location: "Bengaluru",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Manual Testing", "Cypress", "Bug Reporting", "Excel"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹18k–₹25k/month",
    applyUrl: "https://whatfix.com/careers/qa-intern",
    description: "Whatfix is hiring a QA Intern for a 6-month fully remote engagement with its platform quality team. You will learn testing practices applied to a B2B SaaS product used by enterprises worldwide for digital adoption. Interns will own specific test suites, investigate production bugs, and collaborate with developers to improve release quality. This role is an excellent starting point for a career in quality engineering at a globally recognised SaaS company."
  },
  {
    id: 24,
    title: "Java Developer (0–1 yr)",
    company: "Mphasis",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java 11", "Spring MVC", "Oracle DB", "REST"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "4–7 LPA",
    applyUrl: "https://mphasis.com/careers/java-developer",
    description: "Mphasis is recruiting Java Developers with 0–1 year of experience for its Digital Banking engineering practice in Bengaluru. You will be part of a project team delivering digital banking features for a leading US-based financial institution. This involves backend service development using Java 11 and Spring MVC, Oracle database interaction, and REST API design. Mphasis provides structured mentoring and a clear roadmap for progression to Senior Developer within 2 years."
  },
  {
    id: 25,
    title: "Frontend Intern",
    company: "Unacademy",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["React", "Redux", "JavaScript", "Performance Optimisation"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹25k–₹40k/month",
    applyUrl: "https://unacademy.com/careers/frontend-intern",
    description: "Unacademy is hiring Frontend Interns for its learner experience team, where performance and reliability at scale matter. You will build React components used by millions of students preparing for competitive exams. The team moves fast and ships weekly, so you will gain significant hands-on experience quickly. We value curiosity, self-directedness, and a genuine interest in education technology. Strong JavaScript fundamentals are required."
  },
  {
    id: 26,
    title: "SDE Intern",
    company: "Urban Company",
    location: "Gurugram",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Node.js", "MongoDB", "REST APIs", "Git"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹30k–₹45k/month",
    applyUrl: "https://urbancompany.com/careers/sde-intern",
    description: "Urban Company is looking for SDE Interns to join its home services platform team in Gurugram. You will build backend features that connect millions of customers with top-rated service professionals across India and international markets. The role involves Node.js API development, data modelling in MongoDB, and writing automated tests. Engineers here own their features end-to-end and are involved in product decisions from day one."
  },
  {
    id: 27,
    title: "Junior Backend Developer",
    company: "BankBazaar",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "MySQL", "Microservices"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "7–11 LPA",
    applyUrl: "https://bankbazaar.com/info/careers/backend-developer",
    description: "BankBazaar is hiring a Junior Backend Developer for its Financial Marketplace engineering team in Chennai. You will contribute to systems that process personal finance applications including loans, credit cards, and insurance for over 30 million users. The team follows a microservices architecture with Java and Spring Boot at the core. Strong SQL skills, clean code discipline, and experience with unit and integration testing are expected."
  },
  {
    id: 28,
    title: "React Developer (1–3 yrs)",
    company: "Chargebee",
    location: "Chennai",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "JavaScript", "CSS-in-JS"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–16 LPA",
    applyUrl: "https://www.chargebee.com/jobs/react-developer",
    description: "Chargebee, the leading subscription management and billing platform, is hiring a React Developer to work on its customer-facing dashboard experience. You will build complex billing workflows, subscription management UIs, and analytics views used by SaaS companies globally. The team has a mature engineering culture with strong code review practices, detailed documentation standards, and a remote-first mindset. TypeScript experience is a hard requirement."
  },
  {
    id: 29,
    title: "SDE Intern",
    company: "Jupiter",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Spring Boot", "AWS", "Unit Testing"],
    source: "LinkedIn",
    postedDaysAgo: 7,
    salaryRange: "₹35k–₹50k/month",
    applyUrl: "https://jupiter.money/careers/sde-intern",
    description: "Jupiter, the next-generation neobank for India, is hiring SDE Interns to work on its core banking platform and consumer app backend. You will contribute features related to salary accounts, investments, and spending insights used by hundreds of thousands of customers. Jupiter engineering values clarity of thought, strong testing habits, and measured technical decision-making. This internship is a direct pipeline to a full-time SDE-1 offer."
  },
  {
    id: 30,
    title: "Junior Data Analyst",
    company: "Hexaware",
    location: "Mumbai",
    mode: "Onsite",
    experience: "0-1",
    skills: ["SQL", "Power BI", "Excel", "Data Cleaning"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "4–6 LPA",
    applyUrl: "https://hexaware.com/careers/data-analyst",
    description: "Hexaware Technologies is hiring Junior Data Analysts for its Analytics Centre of Excellence in Mumbai. You will be working on client engagements across BFSI and retail sectors, building dashboards in Power BI and writing SQL reports. Hexaware's analytics practice uses a structured delivery model, so you will gain exposure to data governance, report version control, and client presentation skills. Freshers and candidates with 0–1 year of experience are encouraged to apply."
  },
  {
    id: 31,
    title: "Java Developer (0–1 yr)",
    company: "Zensar",
    location: "Pune",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java 8", "Spring", "Hibernate", "Git"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "4.5–7 LPA",
    applyUrl: "https://zensar.com/careers/java-developer",
    description: "Zensar Technologies is hiring Java Developers for its Application Development practice serving European retail and financial clients. You will work in agile sprints, developing and maintaining Java 8 applications using Spring and Hibernate. The role provides mentorship from senior architects and a clear roadmap toward full-stack and cloud specialisation. Good communication skills are required as the role involves direct client interaction for requirement gathering."
  },
  {
    id: 32,
    title: "React Developer (1–3 yrs)",
    company: "Khatabook",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React Native", "JavaScript", "Redux", "Offline-first"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "9–15 LPA",
    applyUrl: "https://khatabook.com/careers/react-developer",
    description: "Khatabook is building the digital finance stack for India's 60 million small businesses and is hiring a React Developer for its mobile-web platform team. You will build features that work reliably on low-end Android devices and in intermittent network conditions — offline-first is a core architectural principle. The team is small, shipping fast, and your work will be seen by merchants across every state in India within days of deployment."
  },
  {
    id: 33,
    title: "Graduate Engineer Trainee",
    company: "Mindtree",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "SQL", "SDLC"],
    source: "Indeed",
    postedDaysAgo: 10,
    salaryRange: "4.5–5.5 LPA",
    applyUrl: "https://mindtree.com/careers/graduate-trainee",
    description: "Mindtree Limited (an LTIMindtree company) is hiring Graduate Engineer Trainees for its Digital and Cloud practices. Successful candidates will complete Mindtree's 90-day Mind-The-Gap onboarding programme before joining a project team. You will be exposed to modern cloud-native architectures, DevOps practices, and enterprise agile delivery. Candidates from any engineering discipline with strong programming aptitude are welcome."
  },
  {
    id: 34,
    title: "Python Developer (Fresher)",
    company: "Persistent Systems",
    location: "Pune",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "FastAPI", "Docker", "Git"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "5–8 LPA",
    applyUrl: "https://persistent.com/careers/python-developer-fresher",
    description: "Persistent Systems is hiring Python Developers fresh out of college for its Global Software Delivery Centre in Pune. You will be building API services and data pipelines for healthcare and life sciences clients using FastAPI and containerised deployments. The team uses test-driven development and CI/CD pipelines as standard practice. A strong academic record and demonstrable Python projects are required for this role."
  },
  {
    id: 35,
    title: "SDE Intern",
    company: "Postman",
    location: "Bengaluru",
    mode: "Remote",
    experience: "Fresher",
    skills: ["JavaScript", "Node.js", "REST APIs", "Testing"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹50k–₹70k/month",
    applyUrl: "https://postman.com/company/careers/sde-intern",
    description: "Postman, the world's leading API platform used by 30 million developers, is hiring SDE Interns to work on its API testing and collaboration features. You will contribute to real features in the Postman desktop and web application, working alongside world-class engineers. The internship is fully remote and structured with mentorship, weekly demos, and a final project presentation. This is one of the most competitive internship programmes in Indian tech."
  },
  {
    id: 36,
    title: "Junior Backend Developer",
    company: "Niyo Solutions",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Node.js", "PostgreSQL", "REST", "RabbitMQ"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "8–13 LPA",
    applyUrl: "https://goniyo.com/careers/backend-developer",
    description: "Niyo, the travel-first neobank, is hiring a Junior Backend Developer for its Card and payments infrastructure team. You will build card-issuance flows, forex handling systems, and transaction APIs that power prepaid cards used by millions of travellers. The role demands reliability, compliance awareness, and great testing discipline. Experience with financial APIs or banking integrations is a significant advantage."
  },
  {
    id: 37,
    title: "QA Intern",
    company: "GlobalBees",
    location: "Delhi",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Test Planning", "Postman", "JIRA"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹20k/month",
    applyUrl: "https://globalbees.com/careers/qa-intern",
    description: "GlobalBees, a consumer brand house operating D2C brands in health, beauty, and home, is hiring QA Interns for its product engineering team. You will test e-commerce flows including checkout, payments, product catalogue, and logistics integrations. The role involves test case authoring, exploratory testing, and defect reporting in JIRA. You will gain exposure to the intersection of retail, technology, and fast-paced startup execution."
  },
  {
    id: 38,
    title: "Data Analyst Intern",
    company: "OkCredit",
    location: "Bengaluru",
    mode: "Remote",
    experience: "Fresher",
    skills: ["SQL", "Python", "Metabase", "Business Metrics"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹18k–₹25k/month",
    applyUrl: "https://okcredit.in/careers/data-analyst-intern",
    description: "OkCredit, the digital ledger app for 10 million Indian SMBs, is hiring a Data Analyst Intern to support its product and growth teams. You will analyse merchant behaviour data, define product metrics, and create reports in Metabase to guide feature decisions. This role offers rare visibility into SMB fintech product analytics in a remote-first environment. Curious candidates with strong SQL foundations and business acumen are ideal."
  },
  {
    id: 39,
    title: "Graduate Engineer Trainee",
    company: "L&T Technology Services",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["C", "Embedded Systems", "Communication Protocols", "Python"],
    source: "Indeed",
    postedDaysAgo: 9,
    salaryRange: "4–5 LPA",
    applyUrl: "https://ltts.com/careers/graduate-engineer-trainee",
    description: "L&T Technology Services (LTTS) is hiring Graduate Engineer Trainees for its Embedded and Industrial Engineering practices in Pune. You will work on cutting-edge product engineering projects for global clients in automotive, aerospace, and heavy engineering. LTTS provides hands-on training in embedded C, RTOS, and communication protocols before project assignment. Graduates with electronics, mechanical, or CS backgrounds are all welcome."
  },
  {
    id: 40,
    title: "Frontend Intern",
    company: "Licious",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "Next.js", "CSS", "API Integration"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹20k–₹30k/month",
    applyUrl: "https://www.licious.in/blog/careers/frontend-intern",
    description: "Licious, India's premier fresh meat and seafood brand, is hiring a Frontend Intern for its consumer technology team. You will build product listing pages, cart flows, and delivery tracking UIs in Next.js for a customer base that expects premium, responsive experiences. The team is small and execution-focused — you will ship real code to real users within your first two weeks. Prior React experience through personal projects is required."
  },
  {
    id: 41,
    title: "Java Developer (0–1 yr)",
    company: "Birlasoft",
    location: "Noida",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "REST", "JUnit"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "4–6.5 LPA",
    applyUrl: "https://birlasoft.com/careers/java-developer",
    description: "Birlasoft is hiring Java Developers for its Enterprise Application Services practice serving clients in manufacturing, pharma, and BFSI domains. You will join an agile team building and maintaining Java Spring Boot services, writing unit tests, and participating in code reviews with senior engineers. Birlasoft values ownership, communication, and disciplined software development practices. Clear growth to Senior SDE within 2–3 years with structured appraisals."
  },
  {
    id: 42,
    title: "React Developer (1–3 yrs)",
    company: "Nagarro",
    location: "Gurugram",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Redux Toolkit", "REST APIs", "Responsive Design"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "9–15 LPA",
    applyUrl: "https://nagarro.com/en/careers/react-developer",
    description: "Nagarro is hiring a React Developer for its Digital Experience Engineering practice, working with global retail and travel clients. You will build high-performance, responsive web UIs and integrate them with microservice backends. Nagarro has a flat, entrepreneurial culture where engineers have direct client exposure and real problem ownership. Strong component design skills, performance optimisation knowledge, and accessibility awareness will set you apart."
  },
  {
    id: 43,
    title: "Junior Backend Developer",
    company: "Setu",
    location: "Bengaluru",
    mode: "Remote",
    experience: "1-3",
    skills: ["Python", "Django", "Financial APIs", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–15 LPA",
    applyUrl: "https://setu.co/careers/backend-developer",
    description: "Setu, Pine Labs' API infrastructure company, is hiring a Junior Backend Developer to build fintech API products used by hundreds of businesses across India. You will work on account aggregation, payment collection, and data consent APIs that form the backbone of India's open finance ecosystem. The team values thoughtful API design, backward compatibility, and security-first thinking. Experience with RBI-regulated financial products is a strong advantage."
  },
  {
    id: 44,
    title: "QA Analyst",
    company: "IBM",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Selenium", "TestNG", "CI/CD", "SQL"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "5–8 LPA",
    applyUrl: "https://ibm.com/employment/in_en/careers/qa-analyst.html",
    description: "IBM India is hiring QA Analysts for its hybrid cloud and AI software product lines. You will be working on automated test suites for enterprise software, integrating tests into CI/CD pipelines and reporting quality metrics to engineering leadership. IBM's QA practice follows a mature quality assurance methodology with mentoring, certification paths, and international collaboration. Candidates with 0–1 year of experience in test automation are preferred."
  },
  {
    id: 45,
    title: "SDE Intern",
    company: "Slice",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Go", "MySQL", "System Design basics", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹35k–₹50k/month",
    applyUrl: "https://sliceit.com/careers/sde-intern",
    description: "Slice, the credit card for the younger generation of India, is hiring SDE Interns to work on its Core Banking and Payments platform. You will develop APIs in Golang, contribute to database schema design, and participate in design reviews for new product features. Slice engineering is output-driven, moving at startup pace with the rigour of a regulated financial institution. Interns here are given meaningful work and real responsibility from week one."
  },
  {
    id: 46,
    title: "Python Developer (Fresher)",
    company: "Hasura",
    location: "Bengaluru",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "GraphQL", "PostgreSQL", "Open Source"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "6–9 LPA",
    applyUrl: "https://hasura.io/careers/python-developer",
    description: "Hasura is hiring a Python Developer to work on its developer tools ecosystem and Cloud platform integrations. Hasura is a globally distributed open-source company, and this role is fully remote from day one. You will contribute to internal tooling, developer education resources, and platform API services. Interest in the open-source community, GraphQL, and developer experience is a strong cultural fit indicator. Your GitHub profile matters as much as your CV."
  },
  {
    id: 47,
    title: "Frontend Intern",
    company: "HCL Technologies",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Angular", "TypeScript", "HTML5", "CSS3"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "₹15k–₹22k/month",
    applyUrl: "https://hcltech.com/careers/frontend-intern",
    description: "HCL Technologies is hiring Frontend Interns for its Digital Business Services practice serving global enterprise clients. You will build Angular-based UIs for insurance, HR, and supply chain applications, working with designers and backend developers across time zones. HCL provides structured training in modern web development practices during the first four weeks before assigning you to a live project. The internship has a strong track record of converting to full-time offers."
  },
  {
    id: 48,
    title: "Junior Backend Developer",
    company: "M2P Fintech",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Card APIs", "Microservices", "AWS"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "8–13 LPA",
    applyUrl: "https://m2pfintech.com/careers/backend-developer",
    description: "M2P Fintech, Asia's leading card issuing and API banking infrastructure provider, is hiring a Junior Backend Developer to work on its card lifecycle and banking API products. You will build and maintain services that power millions of prepaid, credit, and debit cards across India and Southeast Asia. The role requires reliability-focused Java development, experience with third-party financial API integrations, and a compliance-aware engineering mindset."
  },
  {
    id: 49,
    title: "Data Analyst Intern",
    company: "Dunzo",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Superset", "Logistics Data"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹18k–₹25k/month",
    applyUrl: "https://dunzo.com/careers/data-analyst-intern",
    description: "Dunzo's Supply Chain Analytics team is hiring a Data Analyst Intern to help optimise last-mile delivery routes and dark store inventory management. You will analyse delivery time data, identify operational bottlenecks, and present findings directly to operations leadership. This role offers deep exposure to the supply chain analytics of one of India's pioneering quick-commerce companies. A strong interest in logistics and operational efficiency is a big plus."
  },
  {
    id: 50,
    title: "Graduate Engineer Trainee",
    company: "Tech Mahindra",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Telecom basics", "SQL", "Communication"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "3.5–5 LPA",
    applyUrl: "https://techmahindra.com/en-in/careers/graduate-trainee",
    description: "Tech Mahindra is hiring Graduate Engineer Trainees for its Telecom and Digital transformation practices in Hyderabad. You will undergo a 3-month residential foundation programme covering Java, SQL, telecom domain knowledge, and professional communication. After training, you will be deployed on projects with leading global telecommunications and media companies. Tech Mahindra has a dedicated talent development track with annual review cycles and learning allowances."
  },
  {
    id: 51,
    title: "SDE Intern",
    company: "Razorpay",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Node.js", "TypeScript", "MySQL", "System Design basics"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹50k–₹70k/month",
    applyUrl: "https://razorpay.com/jobs/sde-intern",
    description: "Razorpay is hiring SDE Interns across its product engineering teams including Payments, Payroll, and Capital products. You will be contributing to production systems from the very first sprint, paired with a senior engineer who will mentor you throughout. Razorpay interns have historically shipped features that appear in product releases and are cited in team demos. If you want the best internship experience in Indian fintech, this is it."
  },
  {
    id: 52,
    title: "React Developer (1–3 yrs)",
    company: "Postman",
    location: "Bengaluru",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "Electron", "JavaScript", "Developer UX"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "14–20 LPA",
    applyUrl: "https://postman.com/company/careers/react-developer",
    description: "Postman is hiring a React Developer to work on its Electron-based desktop application and web UI. You will build developer-facing UX features for the API testing workspace, request builder, and collection runner used by 30 million developers worldwide. Postman's frontend engineering culture values deep UX thinking, component-level accessibility, and performance profiling. Experience building developer tools or complex form-heavy UIs is highly valued."
  },
  {
    id: 53,
    title: "QA Intern",
    company: "Chargebee",
    location: "Chennai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Selenium", "Python", "API Testing", "Test Design"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹20k–₹30k/month",
    applyUrl: "https://www.chargebee.com/jobs/qa-intern",
    description: "Chargebee's Quality Engineering team is hiring QA Interns for a 6-month structured programme. You will write automated Selenium tests in Python, develop API test suites, and contribute to Chargebee's regression and release-gate test framework. The team follows behaviour-driven development (BDD) practices and uses Pytest and Allure Report. Strong attention to detail, comfort with reading API documentation, and systematic test case thinking are expected."
  },
  {
    id: 54,
    title: "Junior Backend Developer",
    company: "KPIT Technologies",
    location: "Pune",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Automotive APIs", "AUTOSAR", "Git"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "7–11 LPA",
    applyUrl: "https://kpit.com/careers/backend-developer",
    description: "KPIT Technologies, a global pure-play automotive software company, is hiring a Junior Backend Developer to work on software-defined vehicle platforms. You will develop Python-based services for in-vehicle networksand cloud connectivity layers for leading global OEM clients. KPIT is at the forefront of electrification and autonomous driving software engineering. A background in automotive, CAN bus, or embedded Linux is a strong advantage for this role."
  },
  {
    id: 55,
    title: "Python Developer (Fresher)",
    company: "Sonata Software",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Flask", "AWS Lambda", "Pandas"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "4.5–7 LPA",
    applyUrl: "https://sonata-software.com/careers/python-developer",
    description: "Sonata Software is hiring Python Developers for its Platformation practice in Hyderabad. You will build serverless data processing pipelines using AWS Lambda and Python, serving retail and distribution clients across the US and Europe. Sonata's engineering teams follow a product thinking mindset — you are expected to understand the business context of every piece of code you write. Freshers with strong Python fundamentals and AWS knowledge are preferred."
  },
  {
    id: 56,
    title: "SDE Intern",
    company: "BrowserStack",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Ruby", "JavaScript", "Test Frameworks", "Linux"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹45k–₹60k/month",
    applyUrl: "https://browserstack.com/careers/sde-intern",
    description: "BrowserStack is hiring SDE Interns for its core product engineering teams. You will work on features directly in the BrowserStack product — whether Automate, Live, or Percy — contributing to tools used by thousands of engineers from companies like Google, Microsoft, and Twitter. BrowserStack interns are mentored by senior engineers and encouraged to ship code within the first two weeks. Strong language fundamentals and curiosity are the only hard requirements."
  },
  {
    id: 57,
    title: "Java Developer (0–1 yr)",
    company: "Mastech Digital",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java 8", "Spring Boot", "MySQL", "Agile"],
    source: "Indeed",
    postedDaysAgo: 9,
    salaryRange: "4–6 LPA",
    applyUrl: "https://mastechdigital.com/careers/java-developer",
    description: "Mastech Digital is hiring Java Developers for client-facing projects in BFSI and healthcare sectors from its Bengaluru delivery centre. You will write Java Spring Boot services, contribute to REST API design, and collaborate in agile sprints with cross-functional project teams. Mastech provides a clear learning track with quarterly assessments and a technology rotation programme that allows engineers to explore DevOps and cloud disciplines in their second year."
  },
  {
    id: 58,
    title: "Graduate Engineer Trainee",
    company: "Cyient",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "MATLAB", "Engineering Design", "Communication"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "4–5.5 LPA",
    applyUrl: "https://cyient.com/careers/graduate-engineer-trainee",
    description: "Cyient is hiring Graduate Engineer Trainees for its Engineering and Technology Services practice in Hyderabad. You will undergo domain-specific training in aerospace, defence, or geospatial engineering before joining a project team serving global OEM clients. Cyient's engineering practice is recognised by Boeing, Airbus, and GE as a critical delivery partner. This is an excellent opportunity for graduates who want to work on high-stakes, real-world engineering programmes."
  },
  {
    id: 59,
    title: "Data Analyst Intern",
    company: "Mensa Brands",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Excel", "Python", "E-commerce Metrics"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹18k–₹28k/month",
    applyUrl: "https://mensabrands.com/careers/data-analyst-intern",
    description: "Mensa Brands, one of India's fastest-growing D2C brand portfolios, is hiring a Data Analyst Intern to support its performance marketing and brand analytics teams. You will work with e-commerce data across Amazon, Flipkart, and branded websites to generate insights on pricing, inventory, and campaign performance. The role provides exposure to multi-brand analytics in a rapid-acquisition environment. Structured, logical thinking and strong Excel and SQL skills are essential."
  },
  {
    id: 60,
    title: "Junior Backend Developer",
    company: "SAP Labs India",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "SAP BTP", "REST APIs", "Cloud Foundry"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–16 LPA",
    applyUrl: "https://jobs.sap.com/job/Bengaluru-Junior-Backend-Developer",
    description: "SAP Labs India is hiring a Junior Backend Developer to work on SAP Business Technology Platform (BTP) services used by enterprise customers worldwide. You will develop Java-based microservices deployed on Cloud Foundry, integrate SAP's event mesh for asynchronous workflows, and contribute to API governance standards. SAP offers a world-class engineering environment with structured technical mentorship, access to global projects, and SAP Learning Hub credits for continuous certification."
  }
];
